---
title: "elastic_model"
author: "Mark Fier"
date: "2023-04-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(dplyr)
require(glmnet)
require(pROC)
library(readr)
library(caret)
Hotel_Reservations <- read_csv("A&M/STAT656/STAT656Project/FinalProject/Hotel Reservations.csv")
```

## pre-processing

```{r}
str(Hotel_Reservations)

factor_var <- Hotel_Reservations %>%
  select(type_of_meal_plan, room_type_reserved, market_segment_type, booking_status, arrival_year,arrival_month,arrival_date,repeated_guest,required_car_parking_space) %>%
  mutate_all(factor)

quant_var <- Hotel_Reservations %>%
  select(no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,no_of_special_requests,lead_time,avg_price_per_room)

hotel_res_new <- cbind(factor_var, quant_var)
str(hotel_res_new)
```

## data split

```{r}
Y = make.names(hotel_res_new$booking_status)
Y = as.factor(Y)
X = select(hotel_res_new,-booking_status)

set.seed(1)
trainSplit = createDataPartition(y = Y, p = 0.8, list = FALSE)

Ytrain = Y[trainSplit]
Xtrain = X[trainSplit,]
Ytest  = Y[-trainSplit]
Xtest  = X[-trainSplit,]

Xtrain = model.matrix( ~ .-1, Xtrain)
Xtest = model.matrix( ~ .-1, Xtest)
```


## logistic elastic net

```{r}
set.seed(1)
K            = 5
trainControl = trainControl(method = "cv", number = K)
tuneGrid     = expand.grid('alpha'=c(.5, 1, 0),'lambda' = seq(0.0001, .01, length.out = 10))

elasticOut   = train(x = Xtrain, y = Ytrain,
method = "glmnet",
trControl = trainControl, tuneGrid = tuneGrid)#### Answer 1.1

elasticOut$bestTune
```

